### ISSUE TITLE
question marks () instead of glyphs in zsh

### ISSUE THREAD

**Issue by activescott** [infely/nfi#1]
I'm using a zsh terminal on macOS and not seeing most of the glyphs. Screenshot attached

<img width="1291" alt="Screenshot 2023-07-21 at 11 37 39" src="https://github.com/infely/nfi/assets/213716/08f118c1-1a93-400a-80ac-6d038f719528">

**Comment by infely** [comment]
Do you have [nerd font](https://www.nerdfonts.com) installed?

**Comment by activescott** [comment]
I do not. Sorry I guess I should have figured that out 😅
